version: '3.9'
services:
    http:
        image: nginx
        restart: always
        container_name: nginx
        ports:
            - "8002:80"
        volumes:
          - ".:/var/www/html"
          - "./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
            - db
    php:
        build:
            context: ./docker/php
        restart: always
        container_name: php
        environment:
            DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}?serverVersion=14&charset=utf8"
        ports:
            - "9000"
        volumes:
            - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db:
        image: postgres:14.5
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/internal_data/
        volumes:
            - "./docker/postgres/conf:/docker-entrypoint-initdb.d"
            - "./db-data:/var/lib/postgresql/data"
        ports:
            - "5435:5432"
